export const ADD_TO_CARD='ADD_TO_CARD';
export const REMOVE_FROM_CARD='REMOVE_FROM_CARD';
export const ADD_TO_WISHLIST='ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST='REMOVE_FROM_WISHLIST';
export const ADD_TO_ADDRESS='ADD_TO_ADDRESS';
export const REMOVE_FROM_ADDRESS='REMOVE_FROM_ADDRESS';
